# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=254)),
                ('town', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('country', models.CharField(default='Trinidad', max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.CharField(blank=True, max_length=254, null=True)),
                ('bluepens', models.IntegerField(blank=True, default=0, null=True)),
                ('blackpens', models.IntegerField(blank=True, default=0, null=True)),
                ('redpens', models.IntegerField(blank=True, default=0, null=True)),
                ('pencils', models.IntegerField(blank=True, default=0, null=True)),
                ('copybooks', models.IntegerField(blank=True, default=0, null=True)),
                ('gluestick', models.IntegerField(blank=True, default=0, null=True)),
                ('ruler', models.BooleanField(default=False)),
                ('geometryset', models.BooleanField(default=False)),
                ('lettersizepaper', models.IntegerField(blank=True, null=True)),
                ('dressuniform', models.CharField(blank=True, max_length=254, null=True)),
                ('PEuniform', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('classFromDate', models.DateTimeField()),
                ('classToDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.BooleanField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('grade', models.CharField(blank=True, max_length=40, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cell_phone', models.CharField(max_length=12)),
                ('personal_email', models.CharField(max_length=50)),
                ('personal_fax', models.CharField(blank=True, max_length=12, null=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primary.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_address_from', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Address')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('M', 'PTA'), ('D', 'Discipline'), ('E', 'Event'), ('C', 'Closure'), ('A', 'Absentism')], max_length=2)),
                ('teachers_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('principal', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=50)),
                ('fax', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField()),
                ('allergies', models.CharField(blank=True, max_length=254, null=True)),
                ('medical_conditions', models.CharField(blank=True, max_length=254, null=True)),
                ('religious_belief', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Address')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('attended', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegisterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cell_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('personal_email', models.CharField(max_length=50)),
                ('personal_fax', models.CharField(blank=True, max_length=12, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.School')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Multiple Choice'), ('S', 'Short Written Answers'), ('E', 'Essay Type Answers'), ('O', 'Oral'), ('L', 'Lab')], max_length=1)),
                ('topic', models.CharField(max_length=254)),
                ('preparation_material', models.TextField(blank=True, null=True)),
                ('date_set', models.DateField()),
                ('date_corrected', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(default='30 minutes', max_length=50)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student')),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Student'),
        ),
        migrations.AddField(
            model_name='family',
            name='family_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Teacher'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Subject'),
        ),
    ]
