# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 13:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('closedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('term', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2'), ('3', 'Term 3')], default='1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('N', 'NURSERY'), ('INFANTS 1', 'INFANTS 1'), ('INFANTS 2', 'INFANTS 2'), ('STD 1', 'STANDARD 1'), ('STD 2', 'STANDARD 2'), ('STD 3', 'STANDARD 3'), ('STD 4', 'STANDARD 4'), ('STD 5', 'STANDARD 5'), ('FORM 1', 'FORM 1'), ('FORM 2', 'FORM 2'), ('FORM 3', 'FORM 3'), ('FORM 4', 'FORM 4'), ('FORM 5', 'FORM 5'), ('FORM 6', 'FORM 6')], max_length=100, unique=True)),
                ('class_departments', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cell_phone', models.CharField(max_length=12)),
                ('personal_email', models.CharField(max_length=50)),
                ('personal_fax', models.CharField(blank=True, max_length=12, null=True)),
                ('work_name', models.CharField(blank=True, max_length=150, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('relationship', models.CharField(choices=[('M', 'Mother'), ('F', 'Father'), ('B', 'Brother'), ('S', 'Sister'), ('A', 'Aunt'), ('U', 'Uncle'), ('G', 'Grand Parent'), ('C', 'Cousin'), ('L', 'Legal Guardian')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='work_address',
        ),
        migrations.RemoveField(
            model_name='student_parent',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='student_parent',
            name='student',
        ),
        migrations.AddField(
            model_name='class',
            name='classDaysandTime',
            field=models.CharField(default='Monday', help_text='Monday - Wednesday 2pm -3pm, Friday 10:00 am - 11:00 am', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='class_room',
            field=models.CharField(blank=True, default='Room Standard 1 A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('', ''), ('P', 'Primary School'), ('S', 'Secondary School')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ManyToManyField(through='primary.Student_Address', to='primary.Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(through='primary.StudentAttendsClass', to='primary.Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_registered',
            field=models.ManyToManyField(related_name='registers', through='primary.StudentRegisterClass', to='primary.Class'),
        ),
        migrations.AddField(
            model_name='studentregisterclass',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='head_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='primary.ClassName'),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent_Guardian'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent_Guardian'),
        ),
        migrations.AlterField(
            model_name='parent_address',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.Parent_Guardian'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='primary.Address'),
        ),
        migrations.AlterField(
            model_name='studentattendsclass',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='studentregisterclass',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='class',
            name='classFromDate',
        ),
        migrations.RemoveField(
            model_name='class',
            name='classToDate',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('teacher', 'classDaysandTime')]),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student_Parent',
        ),
        migrations.AddField(
            model_name='parent_guardian',
            name='address',
            field=models.ManyToManyField(through='primary.Parent_Address', to='primary.Address'),
        ),
        migrations.AddField(
            model_name='parent_guardian',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary.School'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(to='primary.Parent_Guardian'),
        ),
        migrations.AddField(
            model_name='studentregisterclass',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary.AcademicYear'),
            preserve_default=False,
        ),
    ]
