# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_auto_20170610_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(to='primary.Subject'),
        ),
        migrations.AlterField(
            model_name='classname',
            name='class_departments',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classname',
            name='class_name',
            field=models.CharField(choices=[('N', 'NURSERY'), ('INFANTS 1', 'INFANTS 1'), ('INFANTS 2', 'INFANTS 2'), ('STD 1', 'STANDARD 1'), ('STD 2', 'STANDARD 2'), ('STD 3', 'STANDARD 3'), ('STD 4', 'STANDARD 4'), ('STD 5', 'STANDARD 5'), ('FORM 1', 'FORM 1'), ('FORM 2', 'FORM 2'), ('FORM 3', 'FORM 3'), ('FORM 4', 'FORM 4'), ('FORM 5', 'FORM 5'), ('FORM 6', 'FORM 6')], max_length=100),
        ),
    ]
