# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_auto_20170610_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary.ClassName'),
        ),
    ]
