# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-11 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_auto_20170610_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregisterclass',
            name='academic_year',
        ),
    ]
